### ISSUE TITLE
Complete the draft of DataManager class

### ISSUE THREAD

**Issue by olekscode** [un-olk/Diary#24]
This draft should emulate the work of actual **DataManager** class until the database and all it's controllers will be created.
What I mean is than you should put some random data in plain arrays and implement the basic CRUD-operations on these arrays so that all the other team members could test their own code using your **DataManager** as if it was connected to the actual database.

Later on it should be really easy to replace the arrays with a connection variable (passed to you by **MongoConnect** class) and the array-logic with corresponding queries (without changing the interface of **DataManager** and thus with no harm to the rest of the project).

**Comment by TheQ-v1** [comment]
no need in DataManager for now
